apiVersion : apps/v1 
kind : Deployment
metadata : 
 name : webapp 
spec :
 replicas : 2
 selector : 
  matchLabels : 
   app : webapp
 strategy:
   rollingUpdate:
     maxSurge: 0
     maxUnavailable: 1
   type: RollingUpdate
 template : 
  metadata : 
   labels : 
    app : webapp
  spec : 
   volumes : 
    - name : secret-volume
      secret :
       secretName : secret-file 
   containers :
    - name : web-app-container
<<<<<<< HEAD
      image : 897279496684.dkr.ecr.eu-north-1.amazonaws.com/ecommerce-web-app:2.0.1 
=======
      image : 897279496684.dkr.ecr.eu-north-1.amazonaws.com/ecommerce-web-app:2.0.1
>>>>>>> a560494f0731a4ba2c4f41738a12a595a20e0136
      ports : 
       - containerPort : 8080
      imagePullPolicy: Always
      volumeMounts :
       - name : secret-volume
         readOnly : true
         mountPath : "/etc/secret-volume"
---
apiVersion : v1 
kind : Service
metadata : 
 name : ecommerce-app 
spec : 
 type : LoadBalancer
 selector: 
  app : webapp
 ports : 
  - port : 80
    targetPort : 8080
