apiVersion : apps/v1 
kind : Deployment
metadata : 
 name : webapp 
spec :
 replicas : 2
 selector : 
  matchLabels : 
   app : webapp
 strategy:
   rollingUpdate:
     maxSurge: 0
     maxUnavailable: 1
   type: RollingUpdate
 template : 
  metadata : 
   labels : 
    app : webapp
  spec : 
   containers :
    - name : web-app-container
      image : 897279496684.dkr.ecr.eu-north-1.amazonaws.com/ecommerce-web-app:2.0.3
      ports : 
       - containerPort : 8080
      imagePullPolicy: Always
      env : 
       - name : MYSQL_ROOT_PASSWORD
         valueFrom : 
          secretKeyRef:
            name : secret-env-file
            key : MYSQL_ROOT_PASSWORD
       - name : MYSQL_DATABASE
         valueFrom : 
          secretKeyRef:
            name : secret-env-file
            key : MYSQL_DATABASE
       - name : MYSQL_USER
         valueFrom : 
          secretKeyRef:
            name : secret-env-file
            key : MYSQL_USER
       - name : MYSQL_PASSWORD
         valueFrom : 
          secretKeyRef:
            name : secret-env-file
            key : MYSQL_PASSWORD
       - name : MYSQL_HOST
         valueFrom : 
          secretKeyRef:
            name : secret-env-file
            key : MYSQL_HOST
       - name : MYSQL_PORT
         valueFrom : 
          secretKeyRef:
            name : secret-env-file
            key : MYSQL_PORT
       - name : S3_ACCESS_KEY
         valueFrom : 
          secretKeyRef:
            name : secret-env-file
            key : S3_ACCESS_KEY
       - name : S3_SECRET_KEY
         valueFrom : 
          secretKeyRef:
            name : secret-env-file
            key : S3_SECRET_KEY
       - name : S3_BUCKET_NAME
         valueFrom : 
          secretKeyRef:
            name : secret-env-file
            key : S3_BUCKET_NAME
       - name : MAIL_FROM
         valueFrom : 
          secretKeyRef:
            name : secret-env-file
            key : MAIL_FROM
       - name : MAIL_SMTP_SERVER
         valueFrom : 
          secretKeyRef:
            name : secret-env-file
            key : MAIL_SMTP_SERVER
       - name : MAIL_PASSWORD
         valueFrom : 
          secretKeyRef:
            name : secret-env-file
            key : MAIL_PASSWORD
       - name : ADMIN_EMAIL
         valueFrom : 
          secretKeyRef:
            name : secret-env-file
            key : ADMIN_EMAIL
       - name : ADMIN_NOM
         valueFrom : 
          secretKeyRef:
            name : secret-env-file
            key : ADMIN_NOM
       - name : ADMIN_PASSWORD
         valueFrom :
          secretKeyRef: 
            name : secret-env-file
            key : ADMIN_PASSWORD
---
apiVersion : v1 
kind : Service
metadata : 
 name : ecommerce-app 
spec : 
 type : LoadBalancer
 selector: 
  app : webapp
 ports : 
  - port : 80
    targetPort : 8080
